# SPDX-License-Identifier: GPL-2.0-only
#
obj-$(CONFIG_SECURITY_KAGE) 		+= kage.o
EXTRA_CFLAGS += -Wno-missing-prototypes
kage-y := kage_main.o proc.o runtime.o guards.o funcsig.o guard_printf.o verify.o
